import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { cleanupDir, runSpecdev, assertTest } from './helpers.js'

const TEST_DIR = './tests/test-memory-output'
let failures = 0
let passes = 0

function assert(condition, msg) {
  if (assertTest(condition, msg)) passes++
  else failures++
}

function runCmd(args) {
  return runSpecdev(args)
}

function cleanup() { cleanupDir(TEST_DIR) }

cleanup()
runCmd(['init', `--target=${TEST_DIR}`])

console.log('\nmemory refresh skeleton:')
let result = runCmd(['memory', 'refresh', `--target=${TEST_DIR}`])
assert(result.status === 0, 'memory refresh exits 0')
const memoryPath = join(TEST_DIR, '.specdev', 'project_notes', 'working_memory.md')
const memoryExists = existsSync(memoryPath)
assert(memoryExists, 'working_memory.md created')
const memory = memoryExists ? readFileSync(memoryPath, 'utf-8') : ''
assert(memory.includes('# Working Memory'), 'working memory has heading')
assert(memory.includes('Generated by `specdev memory refresh`'), 'working memory has generated warning')

console.log('\nmemory refresh --json:')
result = runCmd(['memory', 'refresh', `--target=${TEST_DIR}`, '--json'])
assert(result.status === 0, 'memory refresh --json exits 0')
let json = null
try {
  json = JSON.parse(result.stdout)
  assert(true, 'memory refresh --json outputs valid JSON')
} catch {
  assert(false, 'memory refresh --json outputs valid JSON')
}
assert(json?.command === 'memory refresh', 'json command identifies memory refresh')
assert(json?.status === 'ok', 'json status is ok')
assert(json?.output_path === '.specdev/project_notes/working_memory.md', 'json output path is relative')

console.log('\nmemory unknown subcommand:')
result = runCmd(['memory', 'unknown', `--target=${TEST_DIR}`])
assert(result.status === 1, 'unknown memory subcommand fails')
assert(result.stderr.includes('Unknown memory subcommand'), 'unknown subcommand error is clear')

cleanup()
console.log(`\n${passes} passed, ${failures} failed`)
process.exit(failures > 0 ? 1 : 0)
