import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { cleanupDir, runSpecdev, assertTest } from './helpers.js'

const TEST_DIR = './tests/test-memory-output'
let failures = 0
let passes = 0

function assert(condition, msg) {
  if (assertTest(condition, msg)) passes++
  else failures++
}

function runCmd(args) {
  return runSpecdev(args)
}

function cleanup() { cleanupDir(TEST_DIR) }

cleanup()
runCmd(['init', `--target=${TEST_DIR}`])

const specdev = join(TEST_DIR, '.specdev')
writeFileSync(join(specdev, 'project_notes', 'big_picture.md'), [
  '# Project Big Picture',
  '',
  'SpecDev CLI coordinates gated agent workflows with assignment artifacts and review loops.',
  '',
].join('\n'), 'utf-8')

for (const id of ['00001_feature_alpha', '00002_feature_beta', '00003_feature_gamma']) {
  const assignmentPath = join(specdev, 'assignments', id)
  mkdirSync(join(assignmentPath, 'brainstorm'), { recursive: true })
  mkdirSync(join(assignmentPath, 'breakdown'), { recursive: true })
  mkdirSync(join(assignmentPath, 'implementation'), { recursive: true })
  mkdirSync(join(assignmentPath, 'capture'), { recursive: true })
  writeFileSync(join(assignmentPath, 'brainstorm', 'proposal.md'), '# Proposal\n')
  writeFileSync(join(assignmentPath, 'brainstorm', 'design.md'), '# Design\n')
  writeFileSync(join(assignmentPath, 'breakdown', 'plan.md'), '# Plan\n### Task 1: Done\n')
  writeFileSync(join(assignmentPath, 'implementation', 'progress.json'), JSON.stringify({
    total_tasks: 1,
    tasks: [{ number: 1, status: 'completed' }],
  }), 'utf-8')
  writeFileSync(join(assignmentPath, 'status.json'), JSON.stringify({
    brainstorm_approved: true,
    implementation_approved: true,
  }), 'utf-8')
  writeFileSync(join(assignmentPath, 'capture', 'project-notes-diff.md'), '# Diff\n')
  writeFileSync(join(assignmentPath, 'capture', 'workflow-diff.md'), '# Diff\n')
}
mkdirSync(join(specdev, 'knowledge', 'architecture'), { recursive: true })
writeFileSync(join(specdev, 'knowledge', 'architecture', 'alpha-note.md'), '# Alpha Note\n\nUseful architecture fact.\n')
mkdirSync(join(specdev, 'knowledge', '_workflow_feedback'), { recursive: true })
writeFileSync(join(specdev, 'knowledge', '_workflow_feedback', 'beta-note.md'), '# Beta Note\n\nUseful workflow fact.\n')

console.log('\nmemory refresh skeleton:')
let result = runCmd(['memory', 'refresh', `--target=${TEST_DIR}`])
assert(result.status === 0, 'memory refresh exits 0')
const memoryPath = join(TEST_DIR, '.specdev', 'project_notes', 'working_memory.md')
const memoryExists = existsSync(memoryPath)
assert(memoryExists, 'working_memory.md created')
const memory = memoryExists ? readFileSync(memoryPath, 'utf-8') : ''
assert(memory.includes('# Working Memory'), 'working memory has heading')
assert(memory.includes('Generated by `specdev memory refresh`'), 'working memory has generated warning')
assert(memory.includes('SpecDev CLI coordinates gated agent workflows'), 'includes project summary')
assert(memory.includes('## Current Workflow'), 'includes current workflow section')
assert(memory.includes('00003_feature_gamma'), 'includes recent completed assignment')
assert(memory.includes('alpha-note.md'), 'includes alphabetically selected knowledge note')
const wordCount = memory.split(/\s+/).filter(Boolean).length
assert(wordCount <= 800, 'working memory stays within word limit')

const before = memory
result = runCmd(['memory', 'refresh', `--target=${TEST_DIR}`])
const after = readFileSync(memoryPath, 'utf-8')
assert(after === before, 'memory refresh is idempotent with unchanged inputs')

rmSync(join(specdev, '.current'), { force: true })
result = runCmd(['memory', 'refresh', `--target=${TEST_DIR}`])
const noCurrentMemory = readFileSync(memoryPath, 'utf-8')
assert(result.status === 0, 'memory refresh succeeds without current assignment')
assert(noCurrentMemory.includes('No active workflow found.'), 'missing current assignment is handled explicitly')

console.log('\nmemory refresh --json:')
result = runCmd(['memory', 'refresh', `--target=${TEST_DIR}`, '--json'])
assert(result.status === 0, 'memory refresh --json exits 0')
let json = null
try {
  json = JSON.parse(result.stdout)
  assert(true, 'memory refresh --json outputs valid JSON')
} catch {
  assert(false, 'memory refresh --json outputs valid JSON')
}
assert(json?.command === 'memory refresh', 'json command identifies memory refresh')
assert(json?.status === 'ok', 'json status is ok')
assert(json?.output_path === '.specdev/project_notes/working_memory.md', 'json output path is relative')
assert(json?.word_limit === 800, 'json includes word limit')
assert(json?.word_count <= json?.word_limit, 'json word count respects limit')
assert(json?.recent_assignments_limit === 5, 'json includes recent assignment limit')

console.log('\nmemory unknown subcommand:')
result = runCmd(['memory', 'unknown', `--target=${TEST_DIR}`])
assert(result.status === 1, 'unknown memory subcommand fails')
assert(result.stderr.includes('Unknown memory subcommand'), 'unknown subcommand error is clear')

cleanup()
console.log(`\n${passes} passed, ${failures} failed`)
process.exit(failures > 0 ? 1 : 0)
