import { join } from 'path'
import fse from 'fs-extra'
import {
  resolveTargetDir,
  requireSpecdevDirectory,
} from '../utils/command-context.js'

export async function memoryCommand(positionalArgs = [], flags = {}) {
  const subcommand = positionalArgs[0] || 'refresh'
  if (subcommand === 'refresh') return memoryRefreshCommand(flags)

  console.error(`Unknown memory subcommand: ${subcommand}`)
  console.log('Usage: specdev memory refresh')
  process.exitCode = 1
}

async function memoryRefreshCommand(flags = {}) {
  const targetDir = resolveTargetDir(flags)
  const specdevPath = join(targetDir, '.specdev')
  await requireSpecdevDirectory(specdevPath)

  const outputPath = join(specdevPath, 'project_notes', 'working_memory.md')
  const content = '# Working Memory\n\nGenerated by `specdev memory refresh`. Do not edit by hand.\n'
  await fse.ensureDir(join(specdevPath, 'project_notes'))
  await fse.writeFile(outputPath, content, 'utf-8')

  if (flags.json) {
    console.log(JSON.stringify({
      command: 'memory refresh',
      version: 1,
      status: 'ok',
      output_path: '.specdev/project_notes/working_memory.md',
    }, null, 2))
    return
  }

  console.log('Working memory refreshed: .specdev/project_notes/working_memory.md')
}
