export const COMMANDS = [
  { name: 'init', usage: 'init', description: 'Initialize .specdev folder in current directory' },
  { name: 'update', usage: 'update', description: 'Update system files while preserving project files' },
  { name: 'skills', usage: 'skills', description: 'List available skills with activation status' },
  { name: 'skills install', usage: 'skills install', description: 'Install tool skills with coding agent wrappers' },
  { name: 'skills remove', usage: 'skills remove <n>', description: 'Remove an installed tool skill' },
  { name: 'skills sync', usage: 'skills sync', description: 'Reconcile active tools with available skills' },
  { name: 'memory refresh', usage: 'memory refresh', description: 'Regenerate bounded working memory for agents' },
  { name: 'knowledge index', usage: 'knowledge index', description: 'Rebuild SQLite knowledge retrieval cache' },
  { name: 'knowledge search', usage: 'knowledge search <keywords>', description: 'Search indexed SpecDev knowledge' },
  { name: 'knowledge list', usage: 'knowledge list', description: 'List all knowledge files with metadata' },
  { name: 'research', usage: 'research <topic>', description: 'Run the researcher agent for the active assignment' },
  { name: 'agents inspect', usage: 'agents inspect <path>', description: 'Validate and inspect an agent spec' },
  { name: 'start', usage: 'start', description: 'Check/fill project context (big_picture.md)' },
  { name: 'migrate', usage: 'migrate', description: 'Show guided .specdev layout migration workflow' },
  { name: 'migrate legacy-assignments', usage: 'migrate legacy-assignments', description: 'Move legacy root assignment files into phase folders' },
  { name: 'assignment', usage: 'assignment <desc>', description: 'Reserve ID for new assignment, agent names the folder' },
  { name: 'focus', usage: 'focus <id>', description: 'Set active assignment (writes .specdev/.current)' },
  { name: 'discussion', usage: 'discussion <desc>', description: 'Start a parallel brainstorming discussion' },
  { name: 'checkpoint', usage: 'checkpoint <phase>', description: 'Validate phase artifacts before review' },
  { name: 'approve', usage: 'approve <phase>', description: 'Hard gate: approve a phase' },
  { name: 'continue', usage: 'continue', description: 'Detect current state and suggest next action' },
  { name: 'status', usage: 'status', description: 'Emit workflow state for humans or JSON automation' },
  { name: 'next', usage: 'next', description: 'Emit the canonical next workflow action' },
  { name: 'revise', usage: 'revise', description: 'Record design revision, re-enter brainstorm' },
  { name: 'review', usage: 'review <phase>', description: 'Manual review (brainstorm | implementation)' },
  { name: 'check-review', usage: 'check-review', description: 'Read and address review feedback' },
  { name: 'implement', usage: 'implement', description: 'Set up implementation task execution' },
  { name: 'reviewloop', usage: 'reviewloop <phase>', description: 'Automated external review loop (brainstorm | implementation)' },
  { name: 'context', usage: 'context', description: 'Dump project state, commands, knowledge, and skills for agents' },
  { name: 'help', usage: 'help', description: 'Show this help message' },
  { name: 'version', usage: '--version, -v', description: 'Show version number' },
]

export function formatCommandLine(command) {
  return `  ${command.usage.padEnd(20)} ${command.description}`
}
