import { join } from 'path'
import fse from 'fs-extra'
import { scanAssignments, scanSingleAssignment } from './scan.js'
import { detectAssignmentState } from './state.js'
import { resolveCurrentAssignment } from './current.js'

export const MAX_WORKING_MEMORY_WORDS = 800
export const MAX_RECENT_ASSIGNMENTS = 5

const KNOWLEDGE_BRANCHES = ['architecture', 'workflow', '_workflow_feedback']

export async function buildWorkingMemory(specdevPath) {
  const projectSummary = await readProjectSummary(specdevPath)
  const currentWorkflow = await readCurrentWorkflow(specdevPath)
  const recentAssignments = await readRecentCompletedAssignments(specdevPath)
  const knowledgeNotes = await readKnowledgeNotes(specdevPath)

  const sections = {
    header: [
      '# Working Memory',
      '',
      'Generated by `specdev memory refresh`. Do not edit by hand.',
      '',
      'Refresh with: `specdev memory refresh`',
    ],
    project: [
      '',
      '## Project',
      projectSummary || 'No project summary found.',
    ],
    workflow: [
      '',
      '## Current Workflow',
      currentWorkflow || 'No active workflow found.',
    ],
    assignments: [
      '',
      '## Recent Completed Assignments',
      ...formatList(recentAssignments, 'No completed assignments found.'),
    ],
    knowledge: [
      '',
      '## Durable Knowledge',
      ...formatList(knowledgeNotes, 'No durable knowledge notes found.'),
    ],
  }

  const content = boundSections(sections)
  return {
    content,
    wordCount: countWords(content),
    wordLimit: MAX_WORKING_MEMORY_WORDS,
    recentAssignmentsLimit: MAX_RECENT_ASSIGNMENTS,
  }
}

async function readProjectSummary(specdevPath) {
  const bigPicturePath = join(specdevPath, 'project_notes', 'big_picture.md')
  if (!(await fse.pathExists(bigPicturePath))) return null
  const content = await fse.readFile(bigPicturePath, 'utf-8')
  return firstUsefulParagraph(content)
}

async function readCurrentWorkflow(specdevPath) {
  try {
    const current = await resolveCurrentAssignment(specdevPath)
    if (current.error) return null
    const summary = await scanSingleAssignment(current.path, current.name)
    if (!summary) return null
    const detected = await detectAssignmentState(summary, current.path)
    return `${current.name}: ${detected.state}. Next: ${detected.next_action}`
  } catch {
    return null
  }
}

async function readRecentCompletedAssignments(specdevPath) {
  const assignments = await scanAssignments(specdevPath)
  const completed = []
  for (const assignment of assignments) {
    const detected = await detectAssignmentState(assignment, assignment.path)
    if (detected.state === 'completed') {
      completed.push(assignment.name)
    }
  }
  return completed
    .sort((a, b) => b.localeCompare(a))
    .slice(0, MAX_RECENT_ASSIGNMENTS)
    .map((name) => `- ${name}`)
}

async function readKnowledgeNotes(specdevPath) {
  const knowledgePath = join(specdevPath, 'knowledge')
  const notes = []
  for (const branch of KNOWLEDGE_BRANCHES) {
    const branchPath = join(knowledgePath, branch)
    if (!(await fse.pathExists(branchPath))) continue
    const entries = (await fse.readdir(branchPath, { withFileTypes: true }))
      .filter((entry) => entry.isFile() && entry.name.endsWith('.md') && !entry.name.startsWith('.'))
      .map((entry) => entry.name)
      .sort((a, b) => a.localeCompare(b))

    for (const entry of entries) {
      const content = await fse.readFile(join(branchPath, entry), 'utf-8')
      const summary = firstUsefulParagraph(content)
      notes.push(`- ${branch}/${entry}${summary ? `: ${summary}` : ''}`)
    }
  }
  return notes
}

function firstUsefulParagraph(content) {
  const paragraphs = content.split(/\n\s*\n/)
  for (const paragraph of paragraphs) {
    const normalized = paragraph
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'))
      .join(' ')
      .trim()
    if (normalized) return normalized
  }
  return null
}

function formatList(items, emptyMessage) {
  return items.length > 0 ? items : [emptyMessage]
}

function boundSections(sections) {
  let knowledge = sections.knowledge
  let assignments = sections.assignments
  let workflow = sections.workflow

  let content = joinSections({ ...sections, knowledge, assignments, workflow })
  while (countWords(content) > MAX_WORKING_MEMORY_WORDS && knowledge.length > 3) {
    knowledge = knowledge.slice(0, -1)
    content = joinSections({ ...sections, knowledge, assignments, workflow })
  }
  while (countWords(content) > MAX_WORKING_MEMORY_WORDS && assignments.length > 3) {
    assignments = assignments.slice(0, -1)
    content = joinSections({ ...sections, knowledge, assignments, workflow })
  }
  if (countWords(content) > MAX_WORKING_MEMORY_WORDS) {
    workflow = ['', '## Current Workflow', 'Workflow details trimmed to keep working memory bounded.']
    content = joinSections({ ...sections, knowledge, assignments, workflow })
  }
  return content
}

function joinSections(sections) {
  return [
    ...sections.header,
    ...sections.project,
    ...sections.workflow,
    ...sections.assignments,
    ...sections.knowledge,
    '',
  ].join('\n')
}

function countWords(content) {
  return content.split(/\s+/).filter(Boolean).length
}
